authors:
  ob-man:
    name: Alex
    description: Розробник
    avatar: https://avatars.githubusercontent.com/u/17491278
    url: https://github.com/ob-man
  alexvoss:
    name: Alex Voss
    description: Community support
    avatar: https://avatars.githubusercontent.com/u/4134224
    url: https://github.com/alexvoss